### Register

POST http://0.0.0.0:8080/register
Content-Type: application/json

{
  "username": "Paule Pullmo",
  "email": "name@provider.tld",
  "password": "SuperSafePassword"
}

### Login

POST http://0.0.0.0:8080/login
Content-Type: application/json

{
  "email": "name@provider.tld",
  "password": "SuperSafePassword"
}